### PR TITLE
Sx127x fsk regs

### PR DESCRIPTION
**Pull request by jlpoltrack**
Adds the registers for SX127x FSK.

- All original register names left untouched
- All common registers moved to top in a 'common' section
- All fsk registers include '_FSK_'

Rationale - SX127x has lots of registers that function differently when using FSK vs LoRa,  so using the names assigned for LoRa would be confusing, example:

image

### CODE REVIEW

**Comment by olliw42** [comment]
interesting
I'm not totally sure what to think, but having duplicate values in the enum is not the nicest, as well as the disorder. What about separating the FSK ones out into an extra enum SX1276_REG_FSK_ENUM? If that can create ambiguity with some function calls, maybe even just to put also teh common ones into the SX1276_REG_FSK_ENUM enum. Would also allo to order them again.
Just thinking aloud.

**Comment by jlpoltrack** [comment]
> What about separating the FSK ones out into an extra enum SX1276_REG_FSK_ENUM?

That's an option. I think I might prefer 3 enums for the registers then:

1. Common
2. LoRa
3. FSK

**Comment by olliw42** [comment]
ok, three enums.
I would suggest to keep the names for the common enum the same as now. I.e,  SX1276_REG_xxx. The names for the Lora and gfsk ones obviously should be  SX1276_REG_LORA_ and  SX1276_REG_GFSK_ (not FSK since that's what Semtech calls it).
May need some changes in some comments and methods down the road too.
It probably would also be good to leave a comment before the SX1276_REG_xxx enum briefly saying that registers overlap for this one and hence the different enums.

**Comment by jlpoltrack** [comment]
Added the three enums.  Let me know if you want all 'FSK' references to be 'GFSK' - the SX127x datasheet seems to prefer FSK while the SX126x datasheet prefers GFSK.  Seems the only distinction between the two is whether or not one enables gaussian filter.

**Comment by olliw42** [comment]
ah .. I'd like to use what's used in teh data sheet ... if for teh sx1276 it's FSK instead of GFSK I unfiortunately have given you a bad suggestions and would kindly ask you to revert GFSK to FSK ... sorry, I didn't know.

I also think the entries in the SX1276_REG_LORA enum shoudl be named starting with SX1276_REG_LORA_xxx. That's teh pattern I try to follow througout all the code. Will require some changes in the upstream code, but so it be. I rather like clear conventions :)

**Comment by jlpoltrack** [comment]
Updated all entries to use 'LORA_' in both files.

**Comment by olliw42** [comment]
some things are odd in the .h file:
- lines 396 onwards: The section starts with "Enum Definitions Lora Page Registers", but the first two enums do not have 'LoRa' in their name, which I read to mean that they relate to general registers and should move to somewhere else.
- line 568; this should be SX1276_LORA_DETECTION_TRESHOLD_ENUM
- lines 580 onwards: The section starts with "Enum Definitions FSK Registers required for LoRa", but the enums have neither LoRa nor FSK in their name which I read to mean that they relate to general registers and should move to somewhere else.

I think that these register specific enums should come somewhat in sync with their appeareance in the three top enums.

No FSK specific register enums yet. Probably will come later, right.

MANY thx for working through all this!

**Comment by jlpoltrack** [comment]
Reworked the register enums to just have a common and LoRa section.  Will add FSK later if this format works.

**Comment by olliw42** [comment]
will merge now!
excellent baseline, we can improve anytime :)
MANY THX

**Comment by jlpoltrack** [comment]
One note - I do see that the driver sometimes directly calls registers so that will need an update, e.g. https://github.com/olliw42/mLRS/blob/main/mLRS/Common/sx-drivers/sx127x_driver.h#L130

**Comment by olliw42** [comment]
yes, there will have ot be upstream changes when this is being merged. No problem.

it actually makes it a bit nicer, since you only would use _LORA_ options on _LORA_ registers :)

**Pull request merged**
